mallet_files_path: /PathTo/YourMalletFiles/
mallet_state_file: corpus.topic-state.tsv
mallet_topicweights_file: corpus.topics.tsv
mallet_topics_file: corpus.keys.tsv
mallet_wordweights_file: corpus.wordweights.tsv
corpus_path: /PathTo/YourCorpusTXTFiles/
output_path: /PathFor/OutputHTMLFiles/
corpus_title: your_corpus_name